// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVY5i32xN9kA9rcasOzQM1NnPakhDJd-k',
    appId: '1:919185344154:web:ac5c387057d2efc5de4123',
    messagingSenderId: '919185344154',
    projectId: 'save-3e823',
    authDomain: 'save-3e823.firebaseapp.com',
    storageBucket: 'save-3e823.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXfmMsllCCNPh5RgISk5PcfV9fcINhmEQ',
    appId: '1:919185344154:android:4cbea7adf819a0f5de4123',
    messagingSenderId: '919185344154',
    projectId: 'save-3e823',
    storageBucket: 'save-3e823.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXTLk9Xa4CI4fZnT2UhCNt6D0AIo_OfhE',
    appId: '1:919185344154:ios:f4eb5465f91329b1de4123',
    messagingSenderId: '919185344154',
    projectId: 'save-3e823',
    storageBucket: 'save-3e823.appspot.com',
    iosBundleId: 'com.example.growgrail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXTLk9Xa4CI4fZnT2UhCNt6D0AIo_OfhE',
    appId: '1:919185344154:ios:f4eb5465f91329b1de4123',
    messagingSenderId: '919185344154',
    projectId: 'save-3e823',
    storageBucket: 'save-3e823.appspot.com',
    iosBundleId: 'com.example.growgrail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVY5i32xN9kA9rcasOzQM1NnPakhDJd-k',
    appId: '1:919185344154:web:9f52eb7968fc5475de4123',
    messagingSenderId: '919185344154',
    projectId: 'save-3e823',
    authDomain: 'save-3e823.firebaseapp.com',
    storageBucket: 'save-3e823.appspot.com',
  );
}
